const BASE_IMG = 'https://www.jjensen.no/';

const PRODUCTS = [
  // === FERDIGE PRODUKTER — KOKKEKNIVER ===
  {
    id: 'bunka-55-damascus',
    name: 'Bunka 5.5" Damascus',
    category: 'ferdige-produkter',
    subcategory: 'kokkekniver',
    price: 995,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/67616ad45acb6_Bunkaknife5.png',
    description: 'Kokkekniv i VG-10 Damascus stål med ebenholts-skaft og mosaikk-pin.',
    featured: true,
    inStock: true,
  },
  {
    id: 'nakiri-7-damascus',
    name: 'Nakiri 7" Damascus',
    category: 'ferdige-produkter',
    subcategory: 'kokkekniver',
    price: 1395,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/676183fbd29e4_nakirikitchenknife7.png',
    description: 'Grønnsakskniv i VG-10 Damascus stål med ebenholts-skaft og mosaikk-pin.',
    featured: true,
    inStock: true,
  },
  {
    id: 'kiritsuke-82-damascus',
    name: 'Kiritsuke 8.2" Damascus',
    category: 'ferdige-produkter',
    subcategory: 'kokkekniver',
    price: 1295,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/6761966de9e3e_Kiritsuke8.png',
    description: 'Allround kokkekniv i VG-10 Damascus stål med ebenholts-skaft.',
    featured: true,
    inStock: true,
  },
  {
    id: 'chef-9-damascus',
    name: 'Chef 9" Damascus',
    category: 'ferdige-produkter',
    subcategory: 'kokkekniver',
    price: 1375,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/676198ade8551_chefknife9.png',
    description: 'Stor kokkekniv i VG-10 Damascus stål med ebenholts-skaft og mosaikk-pin.',
    featured: false,
    inStock: true,
  },
  {
    id: 'magnetslire-tre',
    name: 'Magnetslire i tre',
    category: 'ferdige-produkter',
    subcategory: 'kokkekniver',
    price: 170,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/6762c76eceee1_magnetsliretreaskkokkekniv.jpg',
    description: 'Magnetisk knivholder i tre. Tilgjengelig i 4 størrelser.',
    featured: false,
    inStock: true,
  },
  // === FERDIGE PRODUKTER — NKD KNIVER ===
  {
    id: 'nkd-korpi-85',
    name: 'NKD Korpi 85',
    category: 'ferdige-produkter',
    subcategory: 'friluftkniver',
    price: 1500,
    oldPrice: 2125,
    image: BASE_IMG + 'web_images/direkteopplastet/654117968f9bd_NKDKorpi85.png',
    description: 'Kompakt fullheftet kniv med 85mm blad i Sandvik 14C28N stål og bjørkeskaft. Inkl. vegetabilgarvet slire.',
    featured: true,
    inStock: true,
  },
  {
    id: 'nkd-forester-100-n690',
    name: 'NKD Forester 100 N690 Bison',
    category: 'ferdige-produkter',
    subcategory: 'friluftkniver',
    price: 1800,
    oldPrice: 2625,
    image: BASE_IMG + 'web_images/direkteopplastet/6541151610b08_NKDForesterN690bison.png',
    description: 'Robust fullheftet kniv med 100mm blad i N690Co stål og Micarta-skaft. Inkl. vegetabilgarvet slire.',
    featured: true,
    inStock: true,
  },
  // === FERDIGE PRODUKTER — HANDLAGEDE KNIVER ===
  {
    id: 'gunnar-momcilovic-nr4',
    name: 'Gunnar Momcilovic Nr 4',
    category: 'ferdige-produkter',
    subcategory: 'handlagede-kniver',
    price: 3500,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/6076adcd7a8ce_handlagetknivgunnarmomcilovicjungeknivjjensen.no.jpg',
    description: 'Foldekniv med messingplater og gravert dekor. Blad og rygg i rustfritt Sandvik 12C27 stål. Totallengde åpen: 170mm.',
    featured: false,
    inStock: true,
  },
  {
    id: 'kay-embretsen-nr6',
    name: 'Kay Embretsen Nr 6',
    category: 'ferdige-produkter',
    subcategory: 'handlagede-kniver',
    price: 7400,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/603e2a3969663_KE7.jpg',
    description: 'Eksklusiv håndlaget kniv med mørkbeiset Koa-skaft og bronsebolster. Håndsmiddd laminert blad med vegetabilgarvet slire. Totallengde: 205mm.',
    featured: false,
    inStock: true,
  },
  // === FERDIGE PRODUKTER — GRANSFORS SKOGSOKSER ===
  {
    id: 'gransfors-kasteoks-490',
    name: 'Gränsfors Kasteøks STD',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 4599,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/62fb82f8c705c_gransforsaxekasteoks.jpg',
    description: 'Kasteøks fra Gränsfors Bruks. Art.nr: 490-2.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-lille-oks-410',
    name: 'Gränsfors Lille Øks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1599,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857c2d479b3_410lillayxan2500x357.jpg',
    description: 'Liten håndøks fra Gränsfors Bruks, perfekt for turer. Art.nr: 410.',
    featured: true,
    inStock: true,
  },
  {
    id: 'gransfors-handoks-413',
    name: 'Gränsfors Håndøks / Kubben',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1699,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857cac03b7f_413kubben2500x357.jpg',
    description: 'Allsidig håndøks fra Gränsfors Bruks. Art.nr: 413.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-villmarksoks-415',
    name: 'Gränsfors Villmarksøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1499,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857c019f4e4_415vildmarksyxa2500x357.jpg',
    description: 'Klassisk villmarksøks fra Gränsfors Bruks. Art.nr: 415.',
    featured: true,
    inStock: true,
  },
  {
    id: 'gransfors-outdoor-425',
    name: 'Gränsfors Outdoor Øks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1799,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857d74a24c2_425outdooraxe2500x357.jpg',
    description: 'Outdoor-øks fra Gränsfors Bruks. Art.nr: 425.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-liten-skogsoks-420',
    name: 'Gränsfors Liten Skogsøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1799,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857e2284950_420litenskogsyxa2500x357.jpg',
    description: 'Liten skogsøks fra Gränsfors Bruks. Art.nr: 420.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-stor-skogsoks-430',
    name: 'Gränsfors Stor Skogsøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1999,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857e61ad1b1_430storskogsyxa500x357.jpg',
    description: 'Stor skogsøks fra Gränsfors Bruks. Art.nr: 430.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-amerikansk-felloks-434',
    name: 'Gränsfors Amerikansk Felløks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 2469,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f857ea5c676e_434americanfellingaxe500x357.jpg',
    description: 'Amerikansk felløks fra Gränsfors Bruks. Bestillingsvare. Art.nr: 434.',
    featured: false,
    inStock: true,
  },
  // === FERDIGE PRODUKTER — GRANSFORS KLOYVEOKSER ===
  {
    id: 'gransfors-minste-kloyveoks',
    name: 'Gränsfors Minste Kløyvøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1899,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/609535bd2a180_gransforsyxaaxeoksminsteklyvoksgransforsbruks.jpg',
    description: 'Minste kløyvøks fra Gränsfors Bruks. Midlertidig utsolgt.',
    featured: false,
    inStock: false,
  },
  {
    id: 'gransfors-liten-kloyveoks',
    name: 'Gränsfors Liten Kløyvøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 1999,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/609535f14b5e6_gransforsyxaaxeokslitenklyvoksgransforsbruks.jpg',
    description: 'Liten kløyvøks fra Gränsfors Bruks. Midlertidig utsolgt.',
    featured: false,
    inStock: false,
  },
  {
    id: 'gransfors-stor-kloyveoks',
    name: 'Gränsfors Stor Kløyvøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 2099,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/6095379ebccf1_gransforsyxaaxeoksstorklyvoksgransforsbruks.jpg',
    description: 'Stor kløyvøks fra Gränsfors Bruks. Midlertidig utsolgt.',
    featured: false,
    inStock: false,
  },
  {
    id: 'gransfors-stor-kloyveoks-lang',
    name: 'Gränsfors Stor Kløyvøks m/langt skaft',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 2299,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/609537a83922d_gransforsyxaaxeoksstorklyvoksgransforsbruks.jpg',
    description: 'Stor kløyvøks med langt skaft fra Gränsfors Bruks. Midlertidig utsolgt.',
    featured: false,
    inStock: false,
  },
  {
    id: 'gransfors-sleggeoks',
    name: 'Gränsfors Sleggeøks',
    category: 'ferdige-produkter',
    subcategory: 'gransfors-okser',
    price: 2399,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/609537d9b6025_gransforsyxaaxeokssleggeoksgransforsbruks.jpg',
    description: 'Sleggeøks fra Gränsfors Bruks. Midlertidig utsolgt.',
    featured: false,
    inStock: false,
  },
  // === FERDIGE PRODUKTER — STARTSETT ===
  {
    id: 'knivmakersett-nr1',
    name: 'Knivmakersett Nr 1',
    category: 'ferdige-produkter',
    subcategory: 'startsett',
    price: 1195,
    oldPrice: 1529,
    image: BASE_IMG + 'web_images/direkteopplastet/609928fbe2acb_startsettnr1knivmakersettnybegynnersettknivmakerutstyr.jpg',
    description: 'Komplett startsett for nybegynnere. Inkl. knivblad, skaftblokk, slireblankt, reimblank, syl, nåler, tråd, kantverktøy, lærfarge og mer.',
    featured: true,
    inStock: true,
  },
  {
    id: 'knivmakersett-nr2',
    name: 'Knivmakersett Nr 2',
    category: 'ferdige-produkter',
    subcategory: 'startsett',
    price: 525,
    oldPrice: 610,
    image: BASE_IMG + 'web_images/direkteopplastet/609927a1efa80_startsettnr2knivmakersettnybegynnersettknivmakerutstyr.jpg',
    description: 'Enkelt startsett for nybegynnere. Inkl. knivblad, skaftblokk, slireblankt, reimblank, syl og nåler.',
    featured: false,
    inStock: true,
  },
  {
    id: 'knivmakersett-nr3',
    name: 'Knivmakersett Nr 3',
    category: 'ferdige-produkter',
    subcategory: 'startsett',
    price: 825,
    oldPrice: 1015,
    image: BASE_IMG + 'web_images/direkteopplastet/60991ef861f34_startsettnr3knivmakersettnybegynnersettknivmakerutstyrmasurlaer.jpg',
    description: 'Startsett med fokus på sliremaking. 3 slireblankt, 3 reimblank, syl, nåler, tråd, kantverktøy og lærfarge.',
    featured: false,
    inStock: true,
  },
  {
    id: 'salmakersett',
    name: 'Salmakersett',
    category: 'ferdige-produkter',
    subcategory: 'startsett',
    price: 1085,
    oldPrice: 1268,
    image: BASE_IMG + 'web_images/direkteopplastet/60992a5e6a9ff_startsettnybegynnersettsalmakersett.jpg',
    description: 'Komplett salmakersett for nybegynnere. Inkl. nåler, sylhåndtak, blokk, syl, kantverktøy, skjærekniv, saumklyp, tråd og mer.',
    featured: false,
    inStock: true,
  },
  // === MATERIALER — BRYNER OG SLIPEUTSTYR ===
  {
    id: 'diamant-keramisk-lommebryne',
    name: 'Diamant/Keramisk Lommebryne',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 395,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/68b19d60c2117_diamantkeramiskslipesteindmd.jpg',
    description: 'Kombinert diamant og keramisk lommebryne.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-brynefil-400-600',
    name: 'Diamant Brynefil 400/600 Korn',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 195,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/68b6d1149c862_brynefil400600grit.jpg',
    description: 'Dobbeltsidig diamant brynefil, 400 og 600 korn.',
    featured: false,
    inStock: true,
  },
  {
    id: 'knivsliper-karbid-keramisk',
    name: 'Knivsliper Karbid/Keramisk',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 95,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/68b0562aa622c_knivsliperlommebrynegul.jpg',
    description: 'Lommeknivsliper med karbid og keramisk.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-benkebryne-3in1',
    name: 'Diamant Benkebryne 150/350/1200',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 1195,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/67ebe051387e9_dmddiamantbryne3in1benkebryne.jpg',
    description: 'Tredobbelt diamantbenkebryne med 150, 350 og 1200 korn.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-benkebryne-600-1200',
    name: 'Diamant Benkebryne 600/1200',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 495,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/62173e8c2555a_brynediamantbryneknivsliperbenkebryne.jpg',
    description: 'Dobbelt diamantbenkebryne med 600 og 1200 korn.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-benkebryne-400-1000',
    name: 'Diamant Benkebryne 400/1000',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 795,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/67ebecb748ebb_benkebryne2in11000grit400grit.jpg',
    description: 'Dobbelt diamantbenkebryne med 400 og 1000 korn.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-foldebryne-400-600',
    name: 'Diamant Foldebryne 400/600',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 395,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/67ebf38504871_foldebryne2in1.jpg',
    description: 'Foldbart dobbelt diamantbryne med 400 og 600 korn.',
    featured: false,
    inStock: true,
  },
  {
    id: 'diamant-brynestav',
    name: 'Diamant Brynestav',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 415,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/682aebb3e4293_diamantslipestl.jpg',
    description: 'Diamantbrynestav for vedlikehold av knivegger.',
    featured: false,
    inStock: true,
  },
  {
    id: 'keramisk-brynestav',
    name: 'Keramisk Brynestav',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 415,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/68306cf6ada1d_slipestavkeramisk.jpg',
    description: 'Keramisk brynestav for finsliping av knivegger.',
    featured: false,
    inStock: true,
  },
  {
    id: 'jj-slipestropp',
    name: 'JJ Slipestropp',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 395,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/605af41a9eb6b_slipestropp.jpg',
    description: 'Slipestropp i lær for polering av knivsegger.',
    featured: false,
    inStock: true,
  },
  {
    id: 'jj-slipestropp-polervoks',
    name: 'JJ Slipestropp + 2 stk polervoks',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 499,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/605af41a9eb6b_slipestropp.jpg',
    description: 'Slipestropp i lær inkl. 2 stk polervoks.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-keramisk-slipsten-403-4',
    name: 'Gränsfors Keramisk Slipsten 403-4',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 489,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f71d10db4d7d_puckgransfors.png',
    description: 'Rund keramisk slipsten (puck) fra Gränsfors Bruks. Art.nr: 403-4.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-oksefil-403-1',
    name: 'Gränsfors Øksefil 403-1',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 469,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f71d2e932be7_yxfil.png',
    description: 'Øksefil fra Gränsfors Bruks for sliping av økseegg. Art.nr: 403-1.',
    featured: false,
    inStock: true,
  },
  {
    id: 'gransfors-diamantfil-403-2',
    name: 'Gränsfors Diamantfil 403-2',
    category: 'materialer',
    subcategory: 'slip-og-polering',
    price: 569,
    oldPrice: null,
    image: BASE_IMG + 'web_images/direkteopplastet/5f71d2e932be7_yxfil.png',
    description: 'Diamantfil fra Gränsfors Bruks. Art.nr: 403-2.',
    featured: false,
    inStock: true,
  },
];

// Hjelpefunksjoner
function getCategories() {
  const cats = [...new Set(PRODUCTS.map(p => p.category))];
  return cats;
}

function getSubcategories(category) {
  return [...new Set(PRODUCTS.filter(p => p.category === category).map(p => p.subcategory))];
}

function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category);
}

function getProductsBySubcategory(subcategory) {
  return PRODUCTS.filter(p => p.subcategory === subcategory);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.featured);
}

function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.subcategory.toLowerCase().includes(q)
  );
}
